TARGET_SCORE = 11
POINTS_UNTIL_SWITCH = 2

CAMERA_FPS = 60 # fast balls at 30fps are so blurred they are unrecognizable
MAX_STORED_BALL_POSITIONS = 5

GAME_PHASE_TIMEOUT_SECONDS = 1

GAME_PHASE_TIMEOUT_FRAMES = CAMERA_FPS * GAME_PHASE_TIMEOUT_SECONDS
FAST_SPEED = 30 # in feet per second

TTS_MODE = True
MUSIC_FOLDER = 'test'
SOUND_EFFECT_FOLDER = 'test'
